Algoritmo "CalculaAreaRetângulo"

Var
lado1:inteiro
lado2:inteiro
area:inteiro
Inicio
 escreval("Digite o valor do primeiro lado do retângulo: ")
 leia(lado1)
 escreval("Digite o valor do segundo lado do retângulo: ")
 leia(lado2)
 
 area <- lado1 * lado2
 
 escreval("O valor da área deste retângulo,com um lado de ", lado1,"m e outro lado ", lado2, "m é:",area, "m²")
 

   
   
Fimalgoritmo